name: security-pipeline
on: [push, pull_request]

permissions:
  contents: read # needed for checkout

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    concurrency:
      group: appsec-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read # needed for checkout
      security-events: write # needed to upload SARIF results
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Gitleaks Scan
        run: docker run --rm -v "$GITHUB_WORKSPACE:/code" zricethezav/gitleaks:latest detect --source="/code" --redact --no-banner

      - name: Zizmor Audit
        uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d # v0.5.0
        with:
          persona: pedantic
          
      - name: Semgrep OSS Scan
        run: |
          docker run --rm -v "$GITHUB_WORKSPACE:/src" returntocorp/semgrep semgrep \
            scan --config="auto" --error --quiet

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@c1824fd6edce30d7ab345a9989de00bbd46ef284 # master
        with:
          scan-type: 'fs'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          format: 'table'