name: security-arsenal
on: [push, pull_request]

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      # zizmor:ignore[unpinned-uses]
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks Core Scan
        run: docker run --rm -v ${{ github.workspace }}:/code zricethezav/gitleaks:latest detect --source="/code" -v --redact

      # zizmor:ignore[unpinned-uses]
      - name: Zizmor Audit
        uses: zizmorcore/zizmor-action@main

      - name: Semgrep OSS Scan (Recursivo)
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep semgrep \
            scan --config="auto" --error

      # zizmor:ignore[unpinned-uses]
      - name: Trivy Scan (SCA & Config)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'